mqtt:
    url: "tcp://127.0.0.1:1883"

plane:
    code: "10010101"

features:
    enable_full_psdk: false
    enable_trace_log: false
    skip_rc: false
    save_kmz_file: true
    use_test_kmz: false
    test_kmz_file_path: "/tmp/kmz/1.kmz"
